name: mitokmer
owner: galaxytrakr
description: Galaxy wrapper for mitokmer.
long_description: |-
  Galaxy wrapper for mitokmer.
homepage_url: https://github.com/mmammel8/mitokmer2
build_source_url: https://github.com/mmammel8/mitokmer2.git
type: unrestricted
categories:
  - "Tools"